"""Add weekly challenge relation

Revision ID: 1a3e89ce4753
Revises: 48923aecacb0
Create Date: 2026-03-03 03:08:22.676572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1a3e89ce4753'
down_revision = '48923aecacb0'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_challenge',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('category', sa.String(), nullable=False),
                    sa.Column('points', sa.Integer(), nullable=False),
                    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('rule_type', sa.String(), nullable=False),
                    sa.Column('rule_config', postgresql.JSONB(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), onupdate=sa.text('CURRENT_TIMESTAMP')),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_challenge')
    # ### end Alembic commands ###
