"""update equipment table with muscle groups

Revision ID: 24684343da0f
Revises: 
Create Date: 2024-11-20 17:40:32.344965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24684343da0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gear', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=0)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gear', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
