"""Make streaks non-null default 0

Revision ID: 30b29f371489
Revises: 6ec7ce03bb6a
Create Date: 2026-02-10 18:12:25.251531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b29f371489'
down_revision = '6ec7ce03bb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # First complete backfill: set all streaks (active/max) to 0 if they are NULL
    op.execute("UPDATE users SET active_streak = 0 WHERE active_streak IS NULL")
    op.execute("UPDATE users SET max_streak = 0 WHERE max_streak IS NULL")

    op.alter_column('users', 'active_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0')
    )

    op.alter_column('users', 'max_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'max_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'active_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
