"""Remove user from reports

Revision ID: 30d67980c5af
Revises: 24684343da0f
Create Date: 2025-02-13 09:07:17.012872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30d67980c5af'
down_revision = '24684343da0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gear', 'cost',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=0)
    op.drop_constraint('report_user_id_fkey', 'report', type_='foreignkey')
    op.drop_column('report', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('report_user_id_fkey', 'report', 'users', ['user_id'], ['id'])
    op.alter_column('gear', 'cost',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    # ### end Alembic commands ###
