"""popular times

Revision ID: 31b1fa20772f
Revises: 
Create Date: 2025-02-28 20:57:19.922403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '31b1fa20772f'
down_revision = None
branch_labels = None
depends_on = None


### Ensures alembic does not try to create enum
day_of_week_enum = postgresql.ENUM(
    'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
    name='dayofweekenum', create_type=False
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gear', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=0)
    
    ### Alembic is running command multiple times.
    op.execute("""
    DO $$ 
    BEGIN 
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hourly_average_capacity') THEN 
            CREATE TABLE hourly_average_capacity (
                id SERIAL PRIMARY KEY, 
                facility_id INTEGER NOT NULL REFERENCES facility(id), 
                average_percent FLOAT NOT NULL, 
                hour_of_day INTEGER NOT NULL, 
                day_of_week dayofweekenum, 
                history NUMERIC[] DEFAULT '{}' NOT NULL
            );
        END IF; 
    END $$;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('hourly_average_capacity')
    # ### end Alembic commands ###

