"""Include last_streak and last_goal_change to User model

Revision ID: 6fb4a21a1201
Revises: 30b29f371489
Create Date: 2026-02-17 10:06:17.931547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb4a21a1201'
down_revision = '30b29f371489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_goal_change', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_streak')
    op.drop_column('users', 'last_goal_change')
    # ### end Alembic commands ###
