"""added encoded_image column to user

Revision ID: add99ce06ff5
Revises: 7245f58bb00a
Create Date: 2025-03-12 18:17:26.681109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add99ce06ff5'
down_revision = '7245f58bb00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encoded_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encoded_image')
    # ### end Alembic commands ###
