"""new migration

Revision ID: c3a3274d78a1
Revises: 24684343da0f
Create Date: 2025-02-05 18:29:56.359089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3a3274d78a1'
down_revision = '24684343da0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gear', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=0)
    
    op.create_table(
        'hourly_average_capacity',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('facility_id', sa.Integer(), sa.ForeignKey("facility.id"), nullable=False),
        sa.Column('average_percent', sa.Float(), nullable=False),
        sa.Column('hour_of_day', sa.Integer(), nullable=False),
        sa.Column('day_of_week', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
                                         name='dayofweekenum'), nullable=True),
        sa.Column('history', postgresql.ARRAY(sa.Numeric()), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gear', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    
    op.drop_table('hourly_average_capacity')
    # ### end Alembic commands ###
