"""Capacity Reminders updated with times for each day

Revision ID: e3903d2cbf9f
Revises: add_friends_table
Create Date: 2025-04-20 19:05:33.884978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3903d2cbf9f'
down_revision = 'add_friends_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capacity_reminder', sa.Column('reminder_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capacity_reminder', 'reminder_schedule')
    # ### end Alembic commands ###
