"""Initial migration

Revision ID: f711f3c11324
Revises: 
Create Date: 2024-11-07 21:01:33.168047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f711f3c11324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gear', 'cost',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=0)
    op.alter_column('equipment', 'categories',
                    new_column_name='muscle_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gear', 'cost',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('equipment', 'muscle_groups',
                    new_column_name='categories')
    # ### end Alembic commands ###
