name: Docker Build & Push and Deploy to uplift-dev

on:
  push:
    branches: [master]

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: cornellappdev/uplift-dev:${{ steps.vars.outputs.sha_short }}
          build-args: |
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=postgres
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PORT=${{ secrets.DB_PORT }}
            FLASK_ENV=development
      - name: Remote SSH and Deploy
        uses: appleboy/ssh-action@master
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          script: |
            touch tags
            source tags
            export IMAGE_TAG=${{ steps.vars.outputs.sha_short }}
            cd docker-compose
            docker stack rm the-stack
            sleep 20s
            sudo systemctl stop nginx
            sudo systemctl restart nginx
            docker stack deploy -c docker-compose.yml the-stack --with-registry-auth
            yes | docker system prune -a
